Dynamic tile arguments
openbikesensor/portal pull request #260
Opened 2022-07-22 11:30 UTC by opatut

Adds filters to the map to dynamically limit the data being parsed.

Fixes #240, #241.

2022-07-27 21:00 UTC, gluap commented on api/obs/api/routes/tiles.py
> +                raise Forbidden()
Tested this before even looking at the code :) Was not disappointed to get a "forbidden".

2022-07-27 21:14 UTC, gluap requested changes
Tested this on my machine, including trying to fetch the private tiles for another user (and being presented with a forbidden error, :no_entry_sign: :+1: as it should be).

There's one privacy issue though: Allowing a time range as narrow as one day allows to see (anonymous) track data. Scenario: see someone riding with an OBS, later narrow the interval to just the day they were riding, switch to "road usage view" and see their (mostly continuous) track. Unless of course there are tons of riders in the area on that day - but that's unlikely on most portal instances.  Example of such a track track that (from the beginning and end not shown in the picture) I was able to identify as mine.

![image](https://user-images.githubusercontent.com/44007906/181372992-8827f408-824f-4afc-98b4-30b7c67466f3.png)

We could combat this by making the selector less precise - Maybe only allowing to select a month, but no day. 

The same with more inbetween steps will be possible with the "before-after" mode by subtracting before and after from the total - also arriving at the usage numbers in the interval between before and after.

I love the functionality though and think it is pretty powerful as a tool for investigation of the impacts of construction works and other temporal changes on the overtaking distance.

2022-07-28 11:38 UTC, opatut commented
Yeah I am unsure about that fact. However, the same is already possible by showing events on the map, which come with the timestamp, so you can reconstruct movement patterns from them, provided there is little data overlap with other tracks (at the moment quite common). Sure, this makes it easier to visualize that, but the data is already there.

In your attack scenario, you still need the mapping of the known timestamp to the user you've seen in real life to be able to extract information, so the leak (mapping a track to a human person) is technically happening outside the platform. Doesn't make it less valid, but harder to combat...

I'd say we round the date to weeks for now (as construction work will often align to weeks), what do you say?

2022-07-28 18:09 UTC, gluap approved these changes
Agreed - Rounding to weeks allows for decent anonymization with decent granularity in evaluation.

2022-07-28 20:05 UTC, merged